BEGIN_VALUES = "qc" --file
ENDING_FLAGS = --language CS

ARVRObjectEnableControl.cs: ARVRObjectEnableControl.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

EnableDisableBehaviour.cs: EnableDisableBehaviour.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

FlashTextDisplay.cs: FlashTextDisplay.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

LookAtCamera.cs: LookAtCamera.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

MoveCamera.cs: MoveCamera.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

RandomizeEffectPositions.cs: RandomizeEffectPositions.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

RotateAroundTransform.cs: RotateAroundTransform.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

SceneSwitcher.cs: SceneSwitcher.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

ShipMover.cs: ShipMover.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Speaker.cs: Speaker.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

WebCamDisplay.cs: WebCamDisplay.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

all: ARVRObjectEnableControl.cs EnableDisableBehaviour.cs FlashTextDisplay.cs LookAtCamera.cs MoveCamera.cs RandomizeEffectPositions.cs RotateAroundTransform.cs SceneSwitcher.cs ShipMover.cs Speaker.cs WebCamDisplay.cs 
	echo "All done."

clean: 
	del ARVRObjectEnableControl.cs EnableDisableBehaviour.cs FlashTextDisplay.cs LookAtCamera.cs MoveCamera.cs RandomizeEffectPositions.cs RotateAroundTransform.cs SceneSwitcher.cs ShipMover.cs Speaker.cs WebCamDisplay.cs 